### ISSUE TITLE
Fantome zip mod issue in LCS MANAGER

### ISSUE THREAD

**Issue by Rech44** [moonshadow565/lolcustomskin-tools#3]
**Hello, I downloaded the fantome master, I try to install it and it says that I have to download the fantome zip mod, I don't know what to do :D**
 
[https://imgur.com/a/8Xm8Z7u](url)

 _**( The link to the image )**_

**Comment by moonshadow565** [comment]
` I have to download the fantome zip mod` 
its any mod packaged for fantome
